# Generated by Django 4.2.4 on 2023-08-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crash_game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crash_Game_Test1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("content", models.CharField(max_length=50, verbose_name="content")),
                ("app_name", models.CharField(max_length=50, verbose_name="app_name")),
                ("test1", models.CharField(max_length=50, verbose_name="test1")),
            ],
        ),
        migrations.CreateModel(
            name="Crash_Game_Test2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("content", models.CharField(max_length=50, verbose_name="content")),
                ("app_name", models.CharField(max_length=50, verbose_name="app_name")),
                ("test2", models.CharField(max_length=50, verbose_name="test2")),
            ],
        ),
        migrations.CreateModel(
            name="Crash_Game_Test3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("content", models.CharField(max_length=50, verbose_name="content")),
                ("app_name", models.CharField(max_length=50, verbose_name="app_name")),
                ("test3", models.CharField(max_length=50, verbose_name="test3")),
            ],
        ),
    ]
