# Generated by Django 4.2.4 on 2023-08-28 19:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("crash_game", "0002_crash_game_test1_crash_game_test2_crash_game_test3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("currency_code", models.CharField(max_length=15)),
                ("budget", models.PositiveBigIntegerField()),
                ("amount", models.PositiveBigIntegerField()),
                ("profit", models.PositiveBigIntegerField(null=True)),
                ("cash_out_multiplier", models.PositiveBigIntegerField(null=True)),
                ("join_time", models.DateTimeField()),
                ("disjoin_time", models.DateTimeField(default=None, null=True)),
                (
                    "disjoin_reason",
                    models.CharField(
                        choices=[
                            ("CRASH", "crash"),
                            ("CASH_OUT", "cash_out"),
                            ("LEAVE", "leave"),
                            ("NOT_FINISH", "not_finish"),
                        ],
                        default="NOT_FINISH",
                        max_length=32,
                    ),
                ),
                (
                    "real_cash_out_multiplier",
                    models.DecimalField(decimal_places=20, max_digits=100, null=True),
                ),
                (
                    "casino_budget",
                    models.DecimalField(decimal_places=20, max_digits=100),
                ),
                (
                    "casino_amount",
                    models.DecimalField(decimal_places=20, max_digits=100),
                ),
                (
                    "casino_profit",
                    models.DecimalField(decimal_places=20, max_digits=100, null=True),
                ),
                (
                    "reported_budget",
                    models.DecimalField(decimal_places=20, max_digits=100),
                ),
                (
                    "reported_amount",
                    models.DecimalField(decimal_places=20, max_digits=100),
                ),
                (
                    "reported_profit",
                    models.DecimalField(decimal_places=20, max_digits=100, null=True),
                ),
            ],
            options={
                "db_table": "igaming_bet",
            },
        ),
        migrations.CreateModel(
            name="Bound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("casino_id", models.UUIDField()),
                ("currency_code", models.CharField(max_length=15)),
                ("money_precision", models.PositiveBigIntegerField()),
                ("min_bet", models.DecimalField(decimal_places=20, max_digits=100)),
                ("max_bet", models.PositiveBigIntegerField()),
                ("max_profit", models.PositiveBigIntegerField()),
                ("version", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "igaming_bound",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "igaming_game",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("casino_id", models.UUIDField()),
                ("casino_name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("external_id", models.CharField(max_length=500)),
                ("last_session", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[("OFFLINE", "offline"), ("ONLINE", "online")],
                        default="OFFLINE",
                        max_length=50,
                    ),
                ),
                ("ban", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "igaming_player",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("position", models.PositiveBigIntegerField()),
                ("multiplier", models.PositiveBigIntegerField()),
                ("multiplier_hash", models.CharField(max_length=300)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("STARTING", "starting"),
                            ("LOCKING", "locking"),
                            ("PLAYING", "playing"),
                            ("ENDING", "ending"),
                        ],
                        max_length=32,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "real_multiplier",
                    models.DecimalField(decimal_places=20, max_digits=100),
                ),
            ],
            options={
                "db_table": "igaming_round",
            },
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("position",), name="unique_round"
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("casino_id", "external_id"), name="unique_player"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_game"),
        ),
        migrations.AddConstraint(
            model_name="bound",
            constraint=models.UniqueConstraint(
                fields=("version", "casino_id"), name="unique_bound"
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="bound",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crash_game.bound"
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crash_game.player"
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crash_game.round"
            ),
        ),
    ]
