# Generated by Django 4.2.4 on 2023-08-29 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crash_game", "0004_delete_game"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Crash_Game_Test1",
        ),
        migrations.DeleteModel(
            name="Crash_Game_Test2",
        ),
        migrations.DeleteModel(
            name="Crash_Game_Test3",
        ),
    ]
